In [2]:
import pandas as pd
import sqlite3

In [3]:
df = pd.read_csv('./backup.csv')

In [4]:
df1 =df.apply(lambda x: x.astype(str).str.lower())

In [5]:
df.isna().sum()

Unnamed: 0              0
Brand                  40
model_name             65
color                  39
seller                  0
Storage_in_GB         108
RAM                   249
Screen_Size_inches    836
Camera                836
Battery_capactiy      646
current_price           0
product_url             0
img_url                 0
dtype: int64

In [6]:
df.duplicated().sum()

628

In [11]:
df.shape

(771, 11)

In [12]:
df.head()

,Brand,model_name,color,seller,Storage_in_GB,RAM,Screen_Size_inches,Camera,Battery_capactiy,current_price,product_url
0,Generic,"105 EG Mobile TA-1459 DS Charcoal Black, Dual Sim",Black,Amazon,1.99,SIM,NaN,NaN,NaN,679,https://www.amazon.eg/-/en/sspa/click?ie=UTF8&...
1,Generic,1,Black,Amazon,15.00,NaN,NaN,NaN,NaN,464,https://www.amazon.eg/-/en/sspa/click?ie=UTF8&...
2,Generic,Nokia 110 Dual SIM Mobile,Black,Amazon,NaN,(&&,NaN,NaN,NaN,553,https://www.amazon.eg/-/en/sspa/click?ie=UTF8&...
3,Nokia,G21,Blue,Amazon,128.00,4GB,NaN,NaN,NaN,"3,999.00",https://www.amazon.eg/-/en/Nokia-G21-Dual-128G...
5,SAMSUNG,Samsung Galaxy A05s,Black,Amazon,128.00,4GB,NaN,NaN,NaN,"5,600.00",https://www.amazon.eg/-/en/Samsung-Galaxy-Andr...

In [13]:
df.tail()

,Brand,model_name,color,seller,Storage_in_GB,RAM,Screen_Size_inches,Camera,Battery_capactiy,current_price,product_url
830,OPPO,A78,Aqua Green,Amazon,128.0,8GB,NaN,NaN,67.0,"8,250.00",https://www.amazon.eg/-/en/Storage-Display-SUP...
831,OPPO,OPPO Find X5,white,Amazon,256.0,8GB,NaN,NaN,NaN,"19,599.00",https://www.amazon.eg/-/en/OPPO-Find-Dual-256G...
832,Huawei,HUW51097LLXY11iBLK,Starry Black,Amazon,128.0,8GB,NaN,NaN,NaN,"12,999.00",https://www.amazon.eg/-/en/HUAWEI-NOVA-11iDual...
833,Xiaomi,NOTE 12S - ONYX BLACK,ONYX BLACK,Amazon,256.0,8GB,NaN,NaN,5000.0,"11,199.00",https://www.amazon.eg/-/en/NOTE-12S-8GB-RAM-25...
835,Generic,Nokia 3310 Dual SIM,Dark Blue,Amazon,16.0,NaN,NaN,NaN,NaN,"1,099.00",https://www.amazon.eg/-/en/3310-Dual-SIM-16-BL...

In [14]:
df.nunique()

Brand                  23
model_name            118
color                  66
seller                  1
Storage_in_GB          16
RAM                    22
Screen_Size_inches      0
Camera                  0
Battery_capactiy       17
current_price         130
product_url           187
dtype: int64

In [17]:
df.drop_duplicates(subset=['model_name'], inplace=True)

In [7]:
df.dropna(subset=['model_name'], inplace=True)

In [8]:
df.drop(axis=1, labels=['img_url', 'Unnamed: 0'], inplace=True)

In [9]:
df.dtypes

Brand                  object
model_name             object
color                  object
seller                 object
Storage_in_GB         float64
RAM                    object
Screen_Size_inches    float64
Camera                float64
Battery_capactiy      float64
current_price          object
product_url            object
dtype: object

In [11]:
db = sqlite3.connect('main_data.sqlit')

In [12]:
courser = db.cursor()

In [10]:
courser.execute('CREATE TABLE IF NOT EXISTS phones (id int, brand text, model_name text, color text, seller text, Storage_in_GB int, RAM int, Screen_Size_inches float, Camera text, Battery_capactiy int, current_price int, product_url text)')

In [11]:
db.commit()

In [18]:
df1.to_sql('phones',db, if_exists='replace', index=True)

771

In [19]:
courser.execute('''
SELECT * FROM phones;
''')

for i, row in enumerate(courser.fetchall()):
    if i == 10 :
        break
    print (row)

(0, 'generic', '105 eg mobile ta-1459 ds charcoal black, dual sim', 'black', 'amazon', '1.99', 'sim', 'nan', 'nan', 'nan', '679', 'https://www.amazon.eg/-/en/sspa/click?ie=utf8&spc=mto0mtaynjg5mjgzmtgwmta2oje3mtmymzgyote6c3bfyxrmx2jyb3dzztozmdaxmzm1mzywnty1mzi6oja6og&url=%2fmobile-phone-ta-1459-charcoal-ramadan%2fdp%2fb0cv3gmyy5%2fref%3dsr_1_1_sspa%3fdib%3deyj2ijoimsj9.dugnsqagmobq6thfyzqjoemqoggwyohhj7ada4auda7pgl8crlpwzjmifvlyq5eqwkpgeplp2xtmm6zvejojjkyasescr1fmsqzl7hwezaz7rcgxric8fathnq4ipuz3bhqz7kv62bfbdsilh9vyblcnow3s27bwaoy02tc1m2ki5ulktfq3pqgjyndtrorfdmjdw22cnomcssdvpjuowvj40xkil_tfsbrzrykcaooeaheqz6icsg6jlmbtvlsqakwj5qezmizakrhegazo4klfkx8tgy_8pranh0gwcmo.4ade55oi_48xcwshs34jmtgahgvpgo04btilhb1ezo4%26dib_tag%3dse%26qid%3d1713238291%26s%3delectronics%26sr%3d1-1-spons%26sp_csd%3dd2lkz2v0tmftzt1zcf9hdgzfynjvd3nl%26psc%3d1')
(1, 'generic', '1', 'black', 'amazon', '15.0', 'nan', 'nan', 'nan', 'nan', '464', 'https://www.amazon.eg/-/en/sspa/click?ie=utf8&spc=mto0mtaynjg5mjgzmtgwmta2oje3mtmymzgyote6c3bfyxrmx2jyb3dzztozmdaxnte4otawotm3mzi6oja6og&url=%2fmobile-phone-105-black-single%2fdp%2fb0cy93tdl8%2fref%3dsr_1_2_sspa%3fdib%3deyj2ijoimsj9.dugnsqagmobq6thfyzqjoemqoggwyohhj7ada4auda7pgl8crlpwzjmifvlyq5eqwkpgeplp2xtmm6zvejojjkyasescr1fmsqzl7hwezaz7rcgxric8fathnq4ipuz3bhqz7kv62bfbdsilh9vyblcnow3s27bwaoy02tc1m2ki5ulktfq3pqgjyndtrorfdmjdw22cnomcssdvpjuowvj40xkil_tfsbrzrykcaooeaheqz6icsg6jlmbtvlsqakwj5qezmizakrhegazo4klfkx8tgy_8pranh0gwcmo.4ade55oi_48xcwshs34jmtgahgvpgo04btilhb1ezo4%26dib_tag%3dse%26qid%3d1713238291%26s%3delectronics%26sr%3d1-2-spons%26sp_csd%3dd2lkz2v0tmftzt1zcf9hdgzfynjvd3nl%26psc%3d1')
(2, 'generic', 'nokia 110 dual sim mobile', 'black', 'amazon', 'nan', '(&&', 'nan', 'nan', 'nan', '553', 'https://www.amazon.eg/-/en/sspa/click?ie=utf8&spc=mto0mtaynjg5mjgzmtgwmta2oje3mtmymzgyote6c3bfyxrmx2jyb3dzztozmdaxmdc3njezmzy5mzi6oja6og&url=%2fmobile-phone-black-ramadan-kareem%2fdp%2fb0cq3pg5wj%2fref%3dsr_1_3_sspa%3fdib%3deyj2ijoimsj9.dugnsqagmobq6thfyzqjoemqoggwyohhj7ada4auda7pgl8crlpwzjmifvlyq5eqwkpgeplp2xtmm6zvejojjkyasescr1fmsqzl7hwezaz7rcgxric8fathnq4ipuz3bhqz7kv62bfbdsilh9vyblcnow3s27bwaoy02tc1m2ki5ulktfq3pqgjyndtrorfdmjdw22cnomcssdvpjuowvj40xkil_tfsbrzrykcaooeaheqz6icsg6jlmbtvlsqakwj5qezmizakrhegazo4klfkx8tgy_8pranh0gwcmo.4ade55oi_48xcwshs34jmtgahgvpgo04btilhb1ezo4%26dib_tag%3dse%26qid%3d1713238291%26s%3delectronics%26sr%3d1-3-spons%26sp_csd%3dd2lkz2v0tmftzt1zcf9hdgzfynjvd3nl%26psc%3d1')
(3, 'nokia', 'g21', 'blue', 'amazon', '128.0', '4gb', 'nan', 'nan', 'nan', '3,999.00', 'https://www.amazon.eg/-/en/nokia-g21-dual-128gb-inches/dp/b0b39lmdkp')
(5, 'samsung', 'samsung galaxy a05s', 'black', 'amazon', '128.0', '4gb', 'nan', 'nan', 'nan', '5,600.00', 'https://www.amazon.eg/-/en/samsung-galaxy-android-smartphone-storage/dp/b0cp45g7c5')
(6, 'samsung', 'galaxy a54', 'awesome graphite', 'amazon', '256.0', '8gb', 'nan', 'nan', '5000.0', '16,840.00', 'https://www.amazon.eg/-/en/samsung-galaxy-a54-graphite-warranty/dp/b0bxp126bq')
(7, 'samsung', 'samsung galaxy a54', 'chartreuse', 'amazon', '256.0', '8gb', 'nan', 'nan', '5000.0', '17,415.00', 'https://www.amazon.eg/-/en/samsung-galaxy-dual-256gb-inches/dp/b0bxnwqzzb')
(8, 'samsung', 'samsung galaxy a05s', 'black', 'amazon', '128.0', '6gb', 'nan', 'nan', 'nan', '6,499.00', 'https://www.amazon.eg/-/en/samsung-galaxy-android-smartphone-storage/dp/b0cp45zgrk')
(10, 'samsung', 'galaxy s24 ultra', 'titanium black', 'amazon', '256.0', '12gb', 'nan', 'nan', 'nan', '1,200.00', 'https://www.amazon.eg/-/en/samsung-android-smartphone-storage-battery/dp/b0cqz22q7l')
(11, 'itel', 'a58 pro', 'multi', 'amazon', '32.0', '2gb', 'nan', 'nan', 'nan', '3,725.00', 'https://www.amazon.eg/-/en/itel-a58-32gb-6-66-inches/dp/b09tvt8zl8')

In [15]:
from langchain_community.llms import Ollama
from langchain_community.agent_toolkits import create_sql_agent
from langchain_community.utilities import SQLDatabase

In [ ]:
llm = Ollama(model='llama3:8b')
conn = SQLDatabase.from_uri('sqlite:///../main_data.sqlit')

In [ ]:
agent = create_sql_agent(llm, db=conn, verbose=True)

In [ ]:
agent.invoke('how may tables in the database')

In [27]:
from langchain.agents.agent_types import AgentType
from langchain_experimental.agents.agent_toolkits import create_csv_agent

In [ ]:
agent = create_csv_agent(
    llm,
    "./backup.csv",
    verbose=True,
    agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
)

In [ ]:
agent.invoke('how many rows in this file')

In [ ]:
import os

In [ ]:
os.getcwd()